# Generated by Django 4.1.13 on 2025-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Live', 'Live'), ('Pre-recorded', 'Pre-recorded'), ('LMS-Based', 'LMS-Based'), ('Read & Acknowledge', 'Read & Acknowledge')], max_length=255)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('duration_in_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
