# Generated by Django 4.1.13 on 2025-03-16 11:54

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_courses_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Live', 'Live'), ('Pre-recorded', 'Pre-recorded'), ('LMS-Based', 'LMS-Based'), ('Read & Acknowledge', 'Read & Acknowledge')], max_length=255)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('duration_in_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.CreateModel(
            name='AcknowledgeModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Courses.module')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            bases=('Courses.module',),
        ),
        migrations.CreateModel(
            name='MediaModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Courses.module')),
                ('url', models.URLField()),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            bases=('Courses.module',),
        ),
    ]
